# Generated by Django 4.2.5 on 2023-09-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=8)),
                ('ano', models.CharField(max_length=4)),
                ('cor', models.CharField(max_length=10)),
                ('dono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data', models.CharField(max_length=50)),
                ('cnh', models.CharField(max_length=2)),
            ],
        ),
    ]
