# Generated by Django 4.2.5 on 2023-09-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lemao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
    ]
